<a href="https://colab.research.google.com/github/DeyraTalentoTech/deyra.notes/blob/main/practicas_gu%C3%ADas_imaster.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print (np.__version__)
print (np.show_config())


1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

In [ ]:
import numpy as np
numeros = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
numeros = np.array(numeros)
print (numeros)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Creación de un ndarray de 2x3 con ceros
matriz_ceros = np.zeros((2, 3))

# Creación de un ndarray de 3x3 con unos
matriz_unos = np.ones((3, 3))

# Creación de un ndarray con valores específicos
matriz_personalizada = np.array([[1, 2, 3], [4, 5, 6]])

# Imprimir los ndarrays
print("Matriz de ceros:")
print(matriz_ceros)

print("\nMatriz de unos:")
print(matriz_unos)

print("\nMatriz personalizada:")
print(matriz_personalizada)


Matriz de ceros:
[[0. 0. 0.]
 [0. 0. 0.]]

Matriz de unos:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matriz personalizada:
[[1 2 3]
 [4 5 6]]


In [ ]:
#Funciones de Numpy
import numpy as np

# Creación de un ndarray con valores del 0 al 9 (sin incluir el 10)
numeros_1 = np.arange(0, 10)
print("Numeros del 0 al 9 (sin incluir el 10):")
print(numeros_1)

# Creación de un ndarray con valores del 1 al 5 de 2  en 2
numeros_2 = np.arange(1, 6, 2)
print("\nNumeros del 1 al 5 de 2 en 2:")
print(numeros_2)

# Creación de un ndarray con valores del 0 al 4 (sin incluir el 4) de 0.5 en 0.5
numeros_3 = np.arange(0, 4, 0.5)
print(numeros_3)

Numeros del 0 al 9 (sin incluir el 10):
[0 1 2 3 4 5 6 7 8 9]

Numeros del 1 al 5 de 2 en 2:
[1 3 5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [ ]:
import numpy as np

# Creación de un ndarray con valores del 0 al 9 (sin incluir el 10)
numeros_1 = np.arange(0, 10)
print(numeros_1)

# Creación de un ndarray con valores del 1 al 5 de 2  en 2
numeros_2 = np.arange(1, 6, 2)
print(numeros_2)

# Creación de un ndarray con valores del 0 al 4 (sin incluir el 4) de 0.5 en 0.5
numeros_3 = np.arange(0, 4, 0.5)
print(numeros_3)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [ ]:
# Creación de un ndarray con 10 valores espaciados uniformementes entre 0 y 1
puntos_1 = np.linspace(0, 1, 10)
print(puntos_1)

# Creación de un ndarray con 5 valores espaciados uniformemente entre 2 y 10
puntos_2 = np.linspace(2, 10, 5)
print(puntos_2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[ 2.  4.  6.  8. 10.]


In [ ]:
# Creación de un ndarray de 3x3 con números aleatorios entre 0 y 1
matriz_aleatoria_1 = np.random.rand(3, 3)
print(matriz_aleatoria_1)

[[0.23574422 0.50926128 0.87834134]
 [0.14836351 0.48815749 0.57846417]
 [0.15027298 0.50637762 0.25523622]]


In [ ]:
# Creación de un ndarray de 5 elementos con números aleatorios entre 0 y 1
Vector_aleatorio_1 = np.random.rand(5)
print(Vector_aleatorio_1)

[0.89767321 0.52460362 0.58877329 0.49308697 0.49281743]


# Características Básicas de ndarray en Numpy

In [ ]:
import numpy as np

# Creación de un ndarray 2D
matriz = np.array([[1, 2, 3], [4, 5, 6]])

# Acceso a un elemento específico (fila 1, columna 2)
elemento = matriz[1, 2]
print(elemento)

# Acceso a una fila completa
fila = matriz[0, :]
print(fila)

# Acceso a una columna completa
columna = matriz[:, 1]
print(columna)

6
[1 2 3]
[2 5]


**Operaciones Matriciales**

In [ ]:
arr = np.array([1, 2, 3])
print(np.sum(arr))

6


In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = array.reshape (3, 2)
flattened_array = array.flatten()
transposed_array = array.transpose()


print("Array original:")
print(array)
print("Array reshape:")
print(reshaped_array)
print("Array Flatten:")
print(flattened_array)
print("Array Transpose:")
print(transposed_array)

Array original:
[[1 2 3]
 [4 5 6]]
Array reshape:
[[1 2]
 [3 4]
 [5 6]]
Array Flatten:
[1 2 3 4 5 6]
Array Transpose:
[[1 4]
 [2 5]
 [3 6]]


**Funciones de Generación de Números Aleatorios**

In [ ]:
import numpy as np

numeros_aleatorios_uniformes = np.random.rand(3)
numeros_aleatorios_enteros = np.random.randint(1, 10, size=5)
numeros_aleatorios_normales = np.random.randn(2, 2)

print(numeros_aleatorios_uniformes)
print(numeros_aleatorios_enteros)
print(numeros_aleatorios_normales)

[0.96346399 0.29331458 0.04372522]
[5 8 2 4 9]
[[-0.23450334 -0.16879993]
 [ 0.09276212 -0.69150377]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Suma elemento por elemento
result = arr1 + arr2
print(result)


[5 7 9]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
result = 2 * arr
print(result)

[2 4 6]


**Suma de matrices**

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = arr1 + arr2
print(result)

[[ 6  8]
 [10 12]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = arr.sum()
print(total_sum)

21


**Funciones de Generación de Números Aleatorios**

In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
average = arr.mean()
print(average)


3.5


In [ ]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
min_value = arr.min()
print(min_value)
max_value = arr.max()
print(max_value)

1
6


In [ ]:
import numpy as np
arr = np.array([5, 2, 8, 1, 7])
idx_min = arr.argmin()
idx_max = arr.argmax()
print(idx_min)
print(idx_max)

3
2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
std_dev = arr.std()
print(std_dev)

1.4142135623730951


**Actividad "Ejercicios Numpy"**

In [ ]:
import numpy as np

# Array unidimensional de longitud 5 con números enteros aleatorios
array_1d = np.random.randint(10, size=5)  # Números enteros aleatorios entre 0 y 9
print("Array unidimensional:", array_1d)

# Array bidimensional de tamaño 3x3 con valores booleanos True
array_2d = np.full((3, 3), True)  # Crea un array de 3x3 llenado con True
print("Array bidimensional:", array_2d)

# Array tridimensional de tamaño 2x3x4 con valores flotantes aleatorios
array_3d = np.random.rand(2, 3, 4)  # Números flotantes aleatorios entre 0 y 1
print("Array tridimensional:", array_3d)

Array unidimensional: [9 4 2 1 3]
Array bidimensional: [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Array tridimensional: [[[0.06520773 0.33948245 0.73081225 0.46585397]
  [0.45158602 0.66302515 0.67822729 0.84932043]
  [0.93578817 0.0309527  0.21482892 0.64832529]]

 [[0.83766857 0.65831905 0.05583295 0.27392023]
  [0.52199811 0.57803577 0.86027389 0.42693304]
  [0.44904979 0.77210103 0.74018392 0.64163207]]]


**Acceso y Modificación de Elementos**

In [ ]:
import numpy as np
#Accede al tercer elemento del array creado en el ejercicio 1a.
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d[2])

# Modica el segundo elemento de la segunda del array creado en el ejercicio 1b para que sea False.
array_2d[1, 1] = False
print(array_2d)

#Calcula la media de los elementos en la tercera dimensión del array creado en el ejercicio 1c.
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.mean())



3
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]
4.5
